### ISSUE TITLE
TND Sprint 4

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick-com#191]
# Integrate [Pagefind](https://pagefind.app/) for search
- [x] Add build step to create index using Rust (Andy)
- [x] Publish to cloudflare pages (Andy)
- [ ] Add Search UI components and connect to interface
- [ ] Add markup to ignore pages from search as needed

# Remove old code
Over the years, I know we've tried several different technologies that I no longer use.  This tasks goes through the code base and removes any 'un-needed' code.  A few I can think of:
- [ ] Netlify CMS
- [ ] Netlify functions
- [ ] Mux video

# Update Images to use new endpoints
- [ ] Make new endpoints (GraphQL)? (Andy)
- [ ] Load data (Andy)
- [ ] Add sample syntax (Andy)
- [ ] How does the hugo strategy handle paging in GraphQL? https://graphql.org/learn/pagination/

# Update Video  to use new endpoints
- [ ] Make new endpoints (GraphQL)? (Andy)
- [ ] Load data (Andy)
- [ ] Add sample syntax (Andy)
- [ ] How does the hugo strategy handle paging in GraphQL? https://graphql.org/learn/pagination/

# New theme  ???
* [Ink Theme](https://github.com/knadh/hugo-ink)

**Comment by budparr** [comment]
you're right on top of all the latest stuff!

**Comment by andreweick** [comment]
Really excited about this -- allows me to get rid of another server!

Also, @regisphilibert talk was **so** good, I'm scrambling trying to change my backend to GRAPHQL before I turn it over to you(s-all) so he can implement that technique he showed!

**Comment by andreweick** [comment]
@budparr need to change the build step to generate the index file though, hence I need to finish #190 first 👍
